name: Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
# Ensure only a single instance of this workflow is running, and cancel any that are in-progress
# before this workflow instance starts
concurrency:
  group: ${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_REPO_READ_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run:
          npm install -g pnpm@6.34.0

      - name: Install
        run: |
          pnpm install --loglevel warn --frozen-lockfile

      - name: Lint
        run: pnpm run lint:all
