name: Protobuf
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
jobs:
  # The submodule commit is an ancestor of the main branch, not some random commit
  submodule-commit-is-ancestor-of-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_REPO_READ_TOKEN }}
      - name: Submodule commit is ancestor of main
        run: |
          git config --global --add safe.directory /__w/v4/v4
          cd packages/v4-protos/proto
          git fetch --unshallow origin main
          git merge-base --is-ancestor HEAD origin/main
