name: Reusable deploy indexer to env

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-to-env:
    name: (${{ inputs.ENVIRONMENT }}) Deploy indexer
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'  # without this, ignite fails.
          submodules: recursive
          token: ${{ secrets.GH_REPO_READ_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get Commit Hash
        run: echo "git_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Print Commit Hash
        run: echo "Git short commit hash is ${{ env.git_hash }}"

      - name: Deploy to ${{ inputs.ENVIRONMENT }} environment using Orb lambda
        id: env-deploy
        uses: dydxprotocol/invoke-aws-lambda@master
        with:
          HTTP_TIMEOUT: 600000  # Ten minutes in milliseconds
          MAX_RETRIES: 3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: us-east-2
          FunctionName: orb_lambda_function
          Payload: |
            {
              "imageTag": "${{ env.git_hash }}",
              "options": {
                "job": "deploy-network-service",
                "serviceName": "indexer",
                "postToSlack": true,
                "username": "Github",
                "isCi": true
              }
            }
